/**
 * Mon API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("MessageApi", () => {
  let instance: api.MessageApi
  beforeEach(function() {
    instance = new api.MessageApi(config)
  });

  test("messageControllerCreate", () => {
    const body: api.CreateMessageDtoImplement = undefined
    return expect(instance.messageControllerCreate(body, {})).resolves.toBe(null)
  })
})

